### PR TITLE
Fix default route metrics labels

### LINKED ISSUE #16: Plugin causes errors in fluentd log: no implicit conversion of nil into Hash
**Describe the bug**
We see the following error message in our fluentd logs:

```
2021-06-21 13:41:10 +0000 [warn]: #0 send an error event stream to @ERROR: error_class=TypeError error="no implicit conversion of nil into Hash" location="/usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-label-router-0.2.8/lib/fluent/plugin/out_label_router.rb:78:in `merge'" tag="kubernetes.var.log.containers.i984d793b-3f7d-4347-9120-f429edfeb9fa-redacted-7ef8eac3ba82fc3587fc15f48fe8b767bf865d88f6c6bda869f635e0e1b9d85e.log"
```

Apparently this in in this plugin.

**Steps to reproduce the issue:**

We deployed the banzai logging-operator according to the documentation but ran into this issue: https://github.com/fluent/fluentd/issues/3382

To fix it we wanted to build a own image with fixed resolv gem. But suddenly we are running in this error here which we didn't notice before.

**Expected behavior**
No errors in the fluentd log

**Additional context**
What we "think" happens:

https://github.com/banzaicloud/fluent-plugin-label-router/blob/master/lib/fluent/plugin/out_label_router.rb#L78 this is where the error happens, so probably `@metrics_labels` is `nil`

We don't really know how it can happen. Maybe it always was an issue but is only triggered now because `get_labels` was introduced in https://github.com/banzaicloud/fluent-plugin-label-router/commit/6bebb8cf70ab4fb2554233c724c55c92eea92c70#diff-770a565d029ee0874311cbe0bf8cdc8019ba5728527ee973e29b2caf4ac3eb82R125

Older images of banzai/fluentd don't ship with this change.

### PR DESCRIPTION
**Pull request by pepov**
Provide a separate configuration option for the default route's metrics labels, and fix nil derefence in case it's not available.

| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| API breaks?     | no
| Deprecations?   | no
| Related tickets | fixes #16 
| License         | Apache 2.0

### What's in this PR?
Fix the nil dereference and add  missing support for metrics labels for the default route.

### CODE REVIEW

File: lib/fluent/plugin/out_label_router.rb [hunk 1]
```diff
@@ -72,15 +74,18 @@ def initialize(rule, router, registry)
...
         def get_labels
-          default = { 'flow': @label }
-          labels = default.merge(@metrics_labels)
-          labels
+          labels = { 'flow': @label, 'id': "default" }
+          if !@metrics_labels.nil?
+            labels.merge(@metrics_labels)
+          else
+            labels
+          end
```
Comment (siliconbrain) [inline lib/fluent/plugin/out_label_router.rb]:
```suggestion
          labels = { 'flow': @label, 'id': "default" }
          !@metrics_labels.nil? ? labels.merge(@metrics_labels) : labels
```

**Review by siliconbrain — APPROVED** [review]

**Review by ahma — APPROVED** [review]
